{
 "title": "delta-spuds",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Credits",
   "type": "text",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "# Spuds\nby Hake Hardware\n\n[YouTube](https://www.youtube.com/channel/UCakvG7QQp4oL0Rtpiei1yKg)\n\n[Substack](https://hakedev.substack.com/)\n\n[Github](https://github.com/hakehardware)\n\nDonations: sm1qqqqqqxl2phuunmsp8dm7hpywszakex34ce52zgdu205q"
   }
  },
  {
   "title": "Spuds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_spuds_online_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nodes Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (node_online{state=\"online\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Nodes Offline",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (node_offline{state=\"offline\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Synced Layer",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sort(node_synced_layer)", "legendFormat": "{{node_name}}" }
   ]
  },
  {
   "title": "Nodes Synced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (node_synced{state=\"synced\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Nodes Not Synced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (node_not_synced{state=\"not synced\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Nodes Smeshing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (node_smeshing{state=\"smeshing\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Nodes Not Smeshing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state) (node_not_smeshing{state=\"not smeshing\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Assigned Layers",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "node_assigned_layers", "legendFormat": "__auto" }
   ]
  }
 ]
}